---
title: Compliance Rates Under Mandatory Seismic Retrofit Ordinances
author:
  - Yating Zhang
  - Juan F. Fung
  - Siamak Sattar
  - TBD
abstract: |
  This article describes the factors that drive compliance rates under mandatory
    seismic retrofit ordinances. Surprisingly, even under mandatory a mandatory
    policy, compliance does not reach 100%. We explain what drives early
    compliance, as well as the factors behind non-compliance.
keywords: seismic retrofit; earthquake resilience; building safety; hazard mitigation
output:
  pdf_document:
    keep_tex: true
    number_sections: true
    citation_package: natbib
header-includes:
  - \usepackage{booktabs}
  - \usepackage{amssymb}
bibliography: retrofit-compliance.bib
documentclass: article
fontsize: 11pt
geometry: margin=1in
linkcolor: blue
---

```{r include=FALSE}
## set global options
knitr::opts_chunk$set(
                    echo=FALSE,
                    message=FALSE,
                    cache=TRUE,
                    cache.path='_cache/',
                    fig.path='figs/'
                  )

options(scipen=999, digits=3)

## load packages
library(here)
library(tidyverse)
```


```{r child='01-intro.Rmd'}
```


# References
